// src/components/TaskComponents/TaskForm.tsx
'use client'
import { useState, useContext, FormEvent, ChangeEvent } from 'react';
import { CgAdd } from 'react-icons/cg';
import { TasksContext } from '@/contexts/tasksContext';

const TaskForm: React.FC = () => {
  const { dispatch } = useContext(TasksContext);
  const [name, setName] = useState<string>('');
  const [description, setDescription] = useState<string>('');

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    // Check that the task name is not empty
    if (!name) return;


    const task = {
      id: Math.floor(Math.random() * 1000),
      name,
      description,
    };

    dispatch({ type: 'ADD_TASK', payload: task });

    setName('');
    setDescription('');
  };

  const handleNameChange = (e: ChangeEvent<HTMLInputElement>) => setName(e.target.value);

  const handleDescriptionChange = (e: ChangeEvent<HTMLInputElement>) => setDescription(e.target.value);

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-3 px-5 mx-auto max-w-lg">
      <input className="border rounded-md p-1" type="text" title="Task Name" placeholder="Task Name" value={name} onChange={handleNameChange} />
      <input
        className="border rounded-md p-1 "
        type="text"
        title="Task Description"
        placeholder="Task Description"
        value={description}
        onChange={handleDescriptionChange}
      />
      <button className="btn btn-primary" type="submit">
        <CgAdd className="text-lg" />
        Add
      </button>
    </form>
  );
};

export default TaskForm;

// src/components/TaskForm.svelte
<script>
	import toast from 'svelte-french-toast';
	import tasksStore from '../stores/tasks-store';

	let title;
	let description;
	let taskNameInput;

	const handleSubmit = (event) => {
		event.preventDefault();
		// Check that the task title is not empty
		if (!title || title === '') {
			toast.error('Please enter a task title');
			return;
		}

		// If there is no description set it to an empty string
		if (!description) description = '';

		tasksStore.addTask({
			id: Math.random().toString(),
			title,
			description
		});

		// Clear the input field & select it again
		title = '';
		description = '';
		taskNameInput.focus();
	};

	const handleClear = () => {
		title = '';
		description = '';
		taskNameInput.focus();
	};
</script>

<form on:submit={handleSubmit}>
	<div class="row d-flex w-100 my-3 justify-content-center g-3">
		<div class="col-12 col-lg-5 col-xl-4">
			<input
				bind:value={title}
				type="text"
				class="form-control"
				placeholder="Task Name"
				aria-label="Task Name"
				bind:this={taskNameInput}
			/>
			<input
				bind:value={description}
				type="text"
				class="form-control my-2"
				placeholder="Task Description"
				aria-label="Task Description"
			/>
		</div>
		<div class="col-12 col-lg-3 col-xl-2">
			<button class="btn btn-outline-primary w-100" type="submit">Add</button>
			<button class="btn btn-outline-warning w-100 my-2" type="button" on:click={handleClear}
				>Clear</button
			>
		</div>
	</div>
</form>
<hr />
